/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppTransactionsIndexRouteImport } from './routes/_app/transactions/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppMembersIndexRouteImport } from './routes/_app/members/index'
import { Route as AppLoansIndexRouteImport } from './routes/_app/loans/index'
import { Route as AppLoanProductsIndexRouteImport } from './routes/_app/loan-products/index'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts/index'
import { Route as AppUsersEditRouteImport } from './routes/_app/users/edit'
import { Route as AppLoansLoanIdRouteImport } from './routes/_app/loans/$loanId'
import { Route as AppMembersEditIndexRouteImport } from './routes/_app/members/edit/index'
import { Route as AppLoansCreateIndexRouteImport } from './routes/_app/loans/create/index'
import { Route as AppLoanProductsEditIndexRouteImport } from './routes/_app/loan-products/edit/index'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMembersIndexRoute = AppMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoansIndexRoute = AppLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoanProductsIndexRoute = AppLoanProductsIndexRouteImport.update({
  id: '/loan-products/',
  path: '/loan-products/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersEditRoute = AppUsersEditRouteImport.update({
  id: '/users/edit',
  path: '/users/edit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoansLoanIdRoute = AppLoansLoanIdRouteImport.update({
  id: '/loans/$loanId',
  path: '/loans/$loanId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMembersEditIndexRoute = AppMembersEditIndexRouteImport.update({
  id: '/members/edit/',
  path: '/members/edit/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoansCreateIndexRoute = AppLoansCreateIndexRouteImport.update({
  id: '/loans/create/',
  path: '/loans/create/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoanProductsEditIndexRoute =
  AppLoanProductsEditIndexRouteImport.update({
    id: '/loan-products/edit/',
    path: '/loan-products/edit/',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/': typeof AppIndexRoute
  '/loans/$loanId': typeof AppLoansLoanIdRoute
  '/users/edit': typeof AppUsersEditRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/loan-products': typeof AppLoanProductsIndexRoute
  '/loans': typeof AppLoansIndexRoute
  '/members': typeof AppMembersIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/transactions': typeof AppTransactionsIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/loan-products/edit': typeof AppLoanProductsEditIndexRoute
  '/loans/create': typeof AppLoansCreateIndexRoute
  '/members/edit': typeof AppMembersEditIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/': typeof AppIndexRoute
  '/loans/$loanId': typeof AppLoansLoanIdRoute
  '/users/edit': typeof AppUsersEditRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/loan-products': typeof AppLoanProductsIndexRoute
  '/loans': typeof AppLoansIndexRoute
  '/members': typeof AppMembersIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/transactions': typeof AppTransactionsIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/loan-products/edit': typeof AppLoanProductsEditIndexRoute
  '/loans/create': typeof AppLoansCreateIndexRoute
  '/members/edit': typeof AppMembersEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_app/': typeof AppIndexRoute
  '/_app/loans/$loanId': typeof AppLoansLoanIdRoute
  '/_app/users/edit': typeof AppUsersEditRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/loan-products/': typeof AppLoanProductsIndexRoute
  '/_app/loans/': typeof AppLoansIndexRoute
  '/_app/members/': typeof AppMembersIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/transactions/': typeof AppTransactionsIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/loan-products/edit/': typeof AppLoanProductsEditIndexRoute
  '/_app/loans/create/': typeof AppLoansCreateIndexRoute
  '/_app/members/edit/': typeof AppMembersEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/logout'
    | '/'
    | '/loans/$loanId'
    | '/users/edit'
    | '/accounts'
    | '/loan-products'
    | '/loans'
    | '/members'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/users'
    | '/loan-products/edit'
    | '/loans/create'
    | '/members/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/logout'
    | '/'
    | '/loans/$loanId'
    | '/users/edit'
    | '/accounts'
    | '/loan-products'
    | '/loans'
    | '/members'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/users'
    | '/loan-products/edit'
    | '/loans/create'
    | '/members/edit'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/logout'
    | '/_app/'
    | '/_app/loans/$loanId'
    | '/_app/users/edit'
    | '/_app/accounts/'
    | '/_app/loan-products/'
    | '/_app/loans/'
    | '/_app/members/'
    | '/_app/reports/'
    | '/_app/settings/'
    | '/_app/transactions/'
    | '/_app/users/'
    | '/_app/loan-products/edit/'
    | '/_app/loans/create/'
    | '/_app/members/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/transactions/': {
      id: '/_app/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/members/': {
      id: '/_app/members/'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/loans/': {
      id: '/_app/loans/'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AppLoansIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/loan-products/': {
      id: '/_app/loan-products/'
      path: '/loan-products'
      fullPath: '/loan-products'
      preLoaderRoute: typeof AppLoanProductsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users/edit': {
      id: '/_app/users/edit'
      path: '/users/edit'
      fullPath: '/users/edit'
      preLoaderRoute: typeof AppUsersEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/loans/$loanId': {
      id: '/_app/loans/$loanId'
      path: '/loans/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof AppLoansLoanIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/members/edit/': {
      id: '/_app/members/edit/'
      path: '/members/edit'
      fullPath: '/members/edit'
      preLoaderRoute: typeof AppMembersEditIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/loans/create/': {
      id: '/_app/loans/create/'
      path: '/loans/create'
      fullPath: '/loans/create'
      preLoaderRoute: typeof AppLoansCreateIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/loan-products/edit/': {
      id: '/_app/loan-products/edit/'
      path: '/loan-products/edit'
      fullPath: '/loan-products/edit'
      preLoaderRoute: typeof AppLoanProductsEditIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppLoansLoanIdRoute: typeof AppLoansLoanIdRoute
  AppUsersEditRoute: typeof AppUsersEditRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
  AppLoanProductsIndexRoute: typeof AppLoanProductsIndexRoute
  AppLoansIndexRoute: typeof AppLoansIndexRoute
  AppMembersIndexRoute: typeof AppMembersIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppLoanProductsEditIndexRoute: typeof AppLoanProductsEditIndexRoute
  AppLoansCreateIndexRoute: typeof AppLoansCreateIndexRoute
  AppMembersEditIndexRoute: typeof AppMembersEditIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppLoansLoanIdRoute: AppLoansLoanIdRoute,
  AppUsersEditRoute: AppUsersEditRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
  AppLoanProductsIndexRoute: AppLoanProductsIndexRoute,
  AppLoansIndexRoute: AppLoansIndexRoute,
  AppMembersIndexRoute: AppMembersIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppLoanProductsEditIndexRoute: AppLoanProductsEditIndexRoute,
  AppLoansCreateIndexRoute: AppLoansCreateIndexRoute,
  AppMembersEditIndexRoute: AppMembersEditIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
